spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TerminPilot
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_USER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

google:
  calendar:
    credentials-path: classpath:google-credentials.json
    id: ${GOOGLE_CALENDAR_ID:}