spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: TerminPilot
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO