spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: TerminPilot
  jpa:
    open-in-view: false

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

logging:
  level:
    root: INFO
